### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by Islandersfan2016** [Silkey-Team/silkey-jwt#21]
redirect user to login page but hide Silkey option - user must login to his account using his current credentials

Which credentials? Silkey or FP accounts?

**Comment by DZariusz** [comment]
You must login user with FP accounts. You can't login with Silkey account because then you create new account for user, but user want to migrate its FP account, not create new one. 
Then you can apply Silkey profile data from token to user account <- and this is migration. Next time user can be logged in just with Silkey.
